export default {
  LOGIN_START: "auth/LOGIN_START",
  LOGIN_SUCCESS: "auth/LOGIN_SUCCESS",
  LOGIN_FAILURE: "auth/LOGIN_FAILURE",

  LOGOUT_START: "auth/LOGOUT_START",
  LOGOUT_SUCCESS: "auth/LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "auth/LOGOUT_FAILURE",

  SIGNUP_START: "auth/SIGNUP_START",
  SIGNUP_SUCCESS: "auth/SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "auth/SIGNUP_FAILURE",

  CLEAR_TOKEN: "CLEAR_TOKEN",
};
