export default {
  GETLISTWORKERS_FAILURE: "GETLISTWORKERS_FAILURE",
  GETLISTWORKERS_START: " GETLISTWORKERS_START",
  GETLISTWORKERS_SUCCESS: "GETLISTWORKERS_SUCCESS",

  DELETEWORKERS_FAILURE: "DELETEWORKERS_FAILURE",
  DELETEWORKERS_START: " DELETEWORKERS_START",
  DELETEWORKERS_SUCCESS: "DELETEWORKERS_SUCCESS",

  SAVEWORKERS_FAILURE: "SAVEWORKERS_FAILURE",
  SAVEWORKERS_START: " SAVEWORKERS_START",
  SAVEWORKERS_SUCCESS: "SAVEWORKERS_SUCCESS",
};
